[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["yongers"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
